stages:
    - debug
    - release
    - deliver
    - trigger

debug:
    stage: debug
    script:
        - ./build debug
    except:
         - master

release:
    stage: release
    script:
        - ./build release
    except:
        - master

delivery:
    stage: deliver
    variables:
        MIU_PATH: "/opt/staging/miu"
        INC_PATH: "$MIU_PATH/include"
        DBG_PATH: "$MIU_PATH/lib-dbg"
        REL_PATH: "$MIU_PATH/lib-rel"
        BIN_PATH: "$MIU_PATH/binaries"
        UT_PATH: "$MIU_PATH/unittest"
    script:
        - ./build debug
        - ./build release

        - mkdir -p $INC_PATH
        - rm -fr $INC_PATH/job
        - cp -frv ./include/job $INC_PATH

        - mkdir -p $DBG_PATH
        - cp -fv debug/libjob.a $DBG_PATH

        - mkdir -p $REL_PATH
        - cp -fv release/libjob.a $REL_PATH

        - mkdir -p $UT_PATH
        - cp -fv release/ut_job $UT_PATH

    only:
        - master

svc:
    stage: trigger
    script:
        - curl -X POST -F token=4583a5f42fb46e80ef3ba95a78c980 -F ref=master $GITLAB_URL/api/v4/projects/15/trigger/pipeline
    only:
        - master
